version: '2'
services:
    hg-init:
        build: .
        volumes:
            - repos:/repos
            - ssh:/home/app/.ssh
        command: ["init"]
    hg:
        depends_on:
            - hg-init
        build: .
        ports:
            - "8000:8000"
            - "8022:8022"
        volumes:
            - repos:/repos
            - ssh:/home/app/.ssh
        command: ["start", "--no-init", "--no-ssh-auth"]

volumes:
    repos:
    ssh:
